/**
 * 國家名稱到 ISO 代碼的映射表
 * 用於從 Google Sheets 的國家名稱推斷 ISO 3166-1 alpha-3 代碼
 */

// 完整的國家名稱到 ISO 代碼映射表
export const countryNameToCodeMap = {
  // 亞洲
  afghanistan: "AFG",
  "åland": "ALA",
  albania: "ALB",
  algeria: "DZA",
  "american samoa": "ASM",
  andorra: "AND",
  angola: "AGO",
  anguilla: "AIA",
  antarctica: "ATA",
  "antigua and barbuda": "ATG",
  argentina: "ARG",
  armenia: "ARM",
  aruba: "ABW",
  australia: "AUS",
  austria: "AUT",
  azerbaijan: "AZE",
  bahamas: "BHS",
  bahrain: "BHR",
  bangladesh: "BGD",
  barbados: "BRB",
  belarus: "BLR",
  belgium: "BEL",
  belize: "BLZ",
  benin: "BEN",
  bermuda: "BMU",
  bhutan: "BTN",
  bolivia: "BOL",
  "bosnia and herzegovina": "BIH",
  botswana: "BWA",
  "bouvet island": "BVT",
  brazil: "BRA",
  "british indian ocean territory": "IOT",
  "brunei darussalam": "BRN",
  bulgaria: "BGR",
  "burkina faso": "BFA",
  burundi: "BDI",
  cambodia: "KHM",
  cameroon: "CMR",
  canada: "CAN",
  "cape verde": "CPV",
  "cayman islands": "CYM",
  "central african republic": "CAF",
  chad: "TCD",
  chile: "CHL",
  china: "CHN",
  "people's republic of china": "CHN",
  "christmas island": "CXR",
  "cocos (keeling) islands": "CCK",
  colombia: "COL",
  comoros: "COM",
  congo: "COG",
  "congo, democratic republic": "COD",
  "cook islands": "COK",
  "costa rica": "CRI",
  "côte d'ivoire": "CIV",
  croatia: "HRV",
  cuba: "CUB",
  cyprus: "CYP",
  "czech republic": "CZE",
  denmark: "DNK",
  djibouti: "DJI",
  dominica: "DMA",
  "dominican republic": "DOM",
  ecuador: "ECU",
  egypt: "EGY",
  "el salvador": "SLV",
  "equatorial guinea": "GNQ",
  eritrea: "ERI",
  estonia: "EST",
  ethiopia: "ETH",
  "falkland islands (malvinas)": "FLK",
  "faroe islands": "FRO",
  fiji: "FJI",
  finland: "FIN",
  france: "FRA",
  "french guiana": "GUF",
  "french polynesia": "PYF",
  "french southern territories": "ATF",
  gabon: "GAB",
  gambia: "GMB",
  georgia: "GEO",
  germany: "DEU",
  ghana: "GHA",
  gibraltar: "GIB",
  greece: "GRC",
  greenland: "GRL",
  grenada: "GRD",
  guadeloupe: "GLP",
  guam: "GUM",
  guatemala: "GTM",
  guernsey: "GGY",
  guinea: "GIN",
  "guinea-bissau": "GNB",
  guyana: "GUY",
  haiti: "HTI",
  "heard island and mcdonald islands": "HMD",
  "holy see (vatican city state)": "VAT",
  honduras: "HND",
  "hong kong": "HKG",
  hungary: "HUN",
  iceland: "ISL",
  india: "IND",
  indonesia: "IDN",
  "iran, islamic republic": "IRN",
  iraq: "IRQ",
  ireland: "IRL",
  "isle of man": "IMN",
  israel: "ISR",
  italy: "ITA",
  jamaica: "JAM",
  japan: "JPN",
  jersey: "JEY",
  jordan: "JOR",
  kazakhstan: "KAZ",
  kenya: "KEN",
  kiribati: "KIR",
  "korea, democratic people's republic": "PRK",
  "korea, republic": "KOR",
  "south korea": "KOR",
  "republic of korea": "KOR",
  kuwait: "KWT",
  kyrgyzstan: "KGZ",
  "lao people's democratic republic": "LAO",
  latvia: "LVA",
  lebanon: "LBN",
  lesotho: "LSO",
  liberia: "LBR",
  "libyan arab jamahiriya": "LBY",
  liechtenstein: "LIE",
  lithuania: "LTU",
  luxembourg: "LUX",
  macao: "MAC",
  "macedonia, the former yugoslav republic": "MKD",
  madagascar: "MDG",
  malawi: "MWI",
  malaysia: "MYS",
  maldives: "MDV",
  mali: "MLI",
  malta: "MLT",
  "marshall islands": "MHL",
  martinique: "MTQ",
  mauritania: "MRT",
  mauritius: "MUS",
  mayotte: "MYT",
  mexico: "MEX",
  "micronesia, federated states": "FSM",
  "moldova, republic": "MDA",
  monaco: "MCO",
  mongolia: "MNG",
  montenegro: "MNE",
  montserrat: "MSR",
  morocco: "MAR",
  mozambique: "MOZ",
  myanmar: "MMR",
  namibia: "NAM",
  nauru: "NRU",
  nepal: "NPL",
  netherlands: "NLD",
  "netherlands antilles": "ANT",
  "new caledonia": "NCL",
  "new zealand": "NZL",
  nicaragua: "NIC",
  niger: "NER",
  nigeria: "NGA",
  niue: "NIU",
  "norfolk island": "NFK",
  "northern mariana islands": "MNP",
  norway: "NOR",
  oman: "OMN",
  pakistan: "PAK",
  palau: "PLW",
  "palestinian territory, occupied": "PSE",
  panama: "PAN",
  "papua new guinea": "PNG",
  paraguay: "PRY",
  peru: "PER",
  philippines: "PHL",
  pitcairn: "PCN",
  poland: "POL",
  portugal: "PRT",
  "puerto rico": "PRI",
  qatar: "QAT",
  reunion: "REU",
  romania: "ROU",
  "russian federation": "RUS",
  russia: "RUS",
  rwanda: "RWA",
  "saint helena": "SHN",
  "saint kitts and nevis": "KNA",
  "saint lucia": "LCA",
  "saint pierre and miquelon": "SPM",
  "saint vincent and the grenadines": "VCT",
  samoa: "WSM",
  "san marino": "SMR",
  "sao tome and principe": "STP",
  "saudi arabia": "SAU",
  senegal: "SEN",
  serbia: "SRB",
  seychelles: "SYC",
  "sierra leone": "SLE",
  singapore: "SGP",
  slovakia: "SVK",
  slovenia: "SVN",
  "solomon islands": "SLB",
  somalia: "SOM",
  "south africa": "ZAF",
  "south georgia and the south sandwich islands": "SGS",
  spain: "ESP",
  "sri lanka": "LKA",
  sudan: "SDN",
  suriname: "SUR",
  "svalbard and jan mayen": "SJM",
  swaziland: "SWZ",
  sweden: "SWE",
  switzerland: "CHE",
  "syrian arab republic": "SYR",
  "taiwan, province of china": "TWN",
  taiwan: "TWN",
  tajikistan: "TJK",
  "tanzania, united republic": "TZA",
  thailand: "THA",
  "timor-leste": "TLS",
  togo: "TGO",
  tokelau: "TKL",
  tonga: "TON",
  "trinidad and tobago": "TTO",
  tunisia: "TUN",
  turkey: "TUR",
  turkmenistan: "TKM",
  "turks and caicos islands": "TCA",
  tuvalu: "TUV",
  uganda: "UGA",
  ukraine: "UKR",
  "united arab emirates": "ARE",
  "united kingdom": "GBR",
  "great britain": "GBR",
  "united states": "USA",
  "united states of america": "USA",
  "united states minor outlying islands": "UMI",
  uruguay: "URY",
  uzbekistan: "UZB",
  vanuatu: "VUT",
  venezuela: "VEN",
  "viet nam": "VNM",
  vietnam: "VNM",
  "virgin islands, british": "VGB",
  "virgin islands, u.s.": "VIR",
  "wallis and futuna": "WLF",
  "western sahara": "ESH",
  yemen: "YEM",
  zambia: "ZMB",
  zimbabwe: "ZWE",
};

/**
 * 從國家名稱推斷 ISO 代碼
 * @param {string} countryName - 國家名稱
 * @returns {string|null} ISO 3166-1 alpha-3 代碼，如果找不到則返回 null
 */
export const getCountryCodeFromName = (countryName) => {
  if (!countryName) return null;

  const normalizedName = countryName
    .toLowerCase()
    .trim()
    .replace(/[^\w\s]/g, ""); // 移除特殊字符

  // 直接匹配
  if (countryNameToCodeMap[normalizedName]) {
    return countryNameToCodeMap[normalizedName];
  }

  // 部分匹配（用於處理變體名稱）
  for (const [name, code] of Object.entries(countryNameToCodeMap)) {
    if (normalizedName.includes(name) || name.includes(normalizedName)) {
      return code;
    }
  }

  return null;
};
